// Portfolio domain types — Phase 1.
//
// Shapes here describe parsed CSV rows + ingest results. Database row
// types are generated by `pnpm db:types`; this file is the contract
// between the parser, the normalizer, and the ingest pipeline.

// =============================================================
// Branded IDs
// =============================================================

export type PortfolioEntityId = string & { __brand: "PortfolioEntityId" };
export type PortfolioPolicyId = string & { __brand: "PortfolioPolicyId" };
export type PortfolioSnapshotId = string & { __brand: "PortfolioSnapshotId" };
export type PortfolioBorrowerRowId = string & {
  __brand: "PortfolioBorrowerRowId";
};
export type PortfolioLoanRowId = string & { __brand: "PortfolioLoanRowId" };
export type PortfolioRepaymentRowId = string & {
  __brand: "PortfolioRepaymentRowId";
};

// =============================================================
// Enums (mirror the SQL enums for cross-layer typing)
// =============================================================

export const PORTFOLIO_ENTITY_CODES = ["crediclaro", "junto_soluciones"] as const;
export type PortfolioEntityCode = (typeof PORTFOLIO_ENTITY_CODES)[number];

export const PORTFOLIO_SNAPSHOT_STATUSES = [
  "in_progress",
  "completed",
  "failed",
] as const;
export type PortfolioSnapshotStatus =
  (typeof PORTFOLIO_SNAPSHOT_STATUSES)[number];

export const PORTFOLIO_LOAN_STATUSES = [
  "closed",
  "performing",
  "delinquent",
  "legacy_delinquent",
] as const;
export type PortfolioLoanStatus = (typeof PORTFOLIO_LOAN_STATUSES)[number];

export const PORTFOLIO_MANAGEMENT_VINTAGES = ["old", "new"] as const;
export type PortfolioManagementVintage =
  (typeof PORTFOLIO_MANAGEMENT_VINTAGES)[number];

export const PORTFOLIO_PRODUCT_GROUPS = [
  "personal_collateralized",
  "personal_uncollateralized",
  "cash_advance",
  "other",
] as const;
export type PortfolioProductGroup = (typeof PORTFOLIO_PRODUCT_GROUPS)[number];

export const PORTFOLIO_SEGMENTS = [
  "old_personal",
  "new_personal",
  "cash_advance",
  "other",
] as const;
export type PortfolioSegment = (typeof PORTFOLIO_SEGMENTS)[number];

export const PORTFOLIO_IFRS_STAGES = [
  "stage_1",
  "stage_2",
  "stage_3",
  "closed",
] as const;
export type PortfolioIfrsStage = (typeof PORTFOLIO_IFRS_STAGES)[number];

export const PORTFOLIO_BORROWER_JOIN_CONFIDENCES = [
  "exact_unique_number",
  "normalized_name",
  "unresolved",
] as const;
export type PortfolioBorrowerJoinConfidence =
  (typeof PORTFOLIO_BORROWER_JOIN_CONFIDENCES)[number];

export const PORTFOLIO_DQ_SEVERITIES = ["ok", "warn", "critical"] as const;
export type PortfolioDqSeverity = (typeof PORTFOLIO_DQ_SEVERITIES)[number];

// =============================================================
// Policy (snapshot of the active row at ingest time)
// =============================================================

export interface PortfolioPolicy {
  id: PortfolioPolicyId;
  effectiveFrom: string; // ISO YYYY-MM-DD
  chargeOffDpdThreshold: number;
  managementCutoffDate: string;
  cashAdvanceAlwaysNew: boolean;
  stage2DpdMin: number;
  stage3DpdMin: number;
  nplDpdMin: number;
  eclStage1Coverage: number | null;
  eclStage2Coverage: number | null;
  eclStage3Coverage: number | null;
}

// =============================================================
// Parsed CSV rows (normalized, money in minor units)
// =============================================================

/**
 * Parsed row from `borrowers_*.csv` after normalization. Strings preserved
 * verbatim where they're free-form (names, addresses); money already in
 * minor units; dates in ISO. The `raw` payload carries every original
 * column for forward-compat.
 */
export interface ParsedBorrowerRow {
  sourceBorrowerId: string;
  uniqueNumber: string | null;
  cedulaNormalized: string | null;
  fullName: string | null;
  lastName: string | null;
  firstName: string | null;
  gender: string | null;
  age: number | null;
  dateOfBirth: string | null; // ISO
  email: string | null;
  mobile: string | null;
  landline: string | null;
  address: string | null;
  city: string | null;
  province: string | null;
  zipcode: string | null;
  country: string | null;
  workingStatus: string | null;
  business: string | null;
  creditScore: number | null;
  loanOfficerRaw: string | null;
  borrowerStatusRaw: string | null;
  createdDate: string | null; // ISO
  numberOfLoans: number | null;
  numberOfOpenLoans: number | null;
  numberOfFullyPaidLoans: number | null;
  numberOfDefaultedLoans: number | null;
  numberOfProcessingLoans: number | null;
  numberOfRestructuredLoans: number | null;
  numberOfDeniedLoans: number | null;
  numberOfNotTakenUpLoans: number | null;
  totalPaidAmountMinor: bigint | null;
  openLoansBalanceMinor: bigint | null;
  normalizedName: string | null;
  raw: Record<string, string>;
}

/**
 * Parsed row from `loans_*.csv` after normalization. Classification
 * fields (status_normalized, management_vintage, etc.) are filled in
 * later by the normalizer with knowledge of the active policy.
 */
export interface ParsedLoanRow {
  sourceLoanId: string;
  sourceLoanNumber: string | null;
  sourceBorrowerRef: string | null;

  productRaw: string | null;
  loanOfficerRaw: string | null;
  releasedDate: string | null;
  maturityDate: string | null;
  durationMonths: number | null;
  repaymentCycle: string | null;
  interestRateRaw: string | null;

  principalAmountMinor: bigint | null;
  balanceAmountMinor: bigint | null;
  totalPrincipalBalanceMinor: bigint | null;
  pendingPrincipalDueMinor: bigint | null;
  pastDueMinor: bigint | null;
  pendingDueMinor: bigint | null;
  paidAmountMinor: bigint | null;
  totalPrincipalPaidMinor: bigint | null;
  totalInterestPaidMinor: bigint | null;
  totalPenaltyPaidMinor: bigint | null;
  totalFeesPaidMinor: bigint | null;
  totalPenaltyBalanceMinor: bigint | null;
  totalFeesBalanceMinor: bigint | null;
  totalInterestBalanceMinor: bigint | null;
  nextInstallmentAmountMinor: bigint | null;
  nextInstallmentDate: string | null;
  lastPaymentAmountMinor: bigint | null;
  lastPaymentDate: string | null;

  daysPastDue: number | null;
  daysPastMaturity: number | null;
  daysToMaturity: number | null;

  bankAccountLoanReleased: string | null;
  statusRaw: string | null;

  raw: Record<string, string>;
}

/**
 * Parsed row from `repayments_*.csv` after normalization.
 */
export interface ParsedRepaymentRow {
  sourceRepaymentId: string;
  sourceLoanId: string;
  sourceBorrowerRef: string | null;

  collectionDate: string | null;
  editDate: string | null;
  method: string | null;
  /** True iff this is real cash inflow (false for write-off / settlement). */
  isCashCollection: boolean;

  principalPaidMinor: bigint;
  interestPaidMinor: bigint;
  penaltyPaidMinor: bigint;
  feesPaidMinor: bigint;
  totalPaidMinor: bigint;

  collectedBy: string | null;
  approvedBy: string | null;
  loanOfficerRaw: string | null;
  description: string | null;
  bankAccountPaymentRaw: string | null;

  raw: Record<string, string>;
}

// =============================================================
// Parser bundle
// =============================================================

export interface ParsedCsvFileMeta {
  filename: string;
  sha256: string;
  byteSize: number;
  rowCount: number;
}

export interface ParsedCsvBundle {
  borrowers: ParsedBorrowerRow[];
  loans: ParsedLoanRow[];
  repayments: ParsedRepaymentRow[];
  meta: {
    borrowers: ParsedCsvFileMeta;
    loans: ParsedCsvFileMeta;
    repayments: ParsedCsvFileMeta;
  };
}

// =============================================================
// Borrower-join resolution (per loan)
// =============================================================

export interface BorrowerJoinResult {
  sourceLoanId: string;
  resolvedSourceBorrowerId: string | null;
  confidence: PortfolioBorrowerJoinConfidence;
}

// =============================================================
// Classification result (one per loan, per policy)
// =============================================================

export interface LoanClassification {
  productGroup: PortfolioProductGroup;
  statusNormalized: PortfolioLoanStatus;
  managementVintage: PortfolioManagementVintage;
  portfolioSegment: PortfolioSegment;
  ifrsStage: PortfolioIfrsStage;
  isNpl: boolean;
}

// =============================================================
// Ingest contract
// =============================================================

export interface IngestArgs {
  entityCode: PortfolioEntityCode;
  snapshotDate: string; // ISO YYYY-MM-DD
  bundle: ParsedCsvBundle;
  uploadedBy?: string | null;
}

export interface IngestResult {
  snapshotId: PortfolioSnapshotId;
  status: PortfolioSnapshotStatus;
  borrowerRowCount: number;
  loanRowCount: number;
  repaymentRowCount: number;
  loansWithBorrowerMatch: number;
  loansWithoutBorrowerMatch: number;
  dqMetrics: DqMetric[];
}

// =============================================================
// Data quality
// =============================================================

export interface DqMetric {
  metric: string;
  valueNumeric: number | null;
  valueText: string | null;
  severity: PortfolioDqSeverity;
  detail: Record<string, unknown>;
}
